// <auto-generated> Sleipnir client stub — generated by sleipnir-gen (--lang cs). Do not edit.
// Generated from Sleipnir runtime discovery. The C# classes ARE the contract.
// Properties are camelCase on the wire; [JsonPropertyName] maps them to PascalCase POCOs.
// Requires the SleipnirClient NuGet package (SleipnirCall, SleipnirRestJsonClient, ISleipnirClient).
// The root client is named SleipnirGeneratedClient (not SleipnirClient) to avoid a collision
// with the global SleipnirClient namespace (the runtime's SleipnirClient.Sleipnir).
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using SleipnirClient.Sleipnir;
using SleipnirCommon.Models;

namespace Sleipnir.Generated
{
    public class StockInfo
    {
        [JsonPropertyName("articleId")]
        public int? ArticleId { get; set; }
        [JsonPropertyName("inStock")]
        public int? InStock { get; set; }
    }

    public class OrderLine
    {
        [JsonPropertyName("articleId")]
        public int? ArticleId { get; set; }
        [JsonPropertyName("qty")]
        public int? Qty { get; set; }
    }

    public class Article
    {
        [JsonPropertyName("id")]
        public int? Id { get; set; }
        [JsonPropertyName("name")]
        public string? Name { get; set; }
        [JsonPropertyName("price")]
        public decimal? Price { get; set; }
    }

    public class Order
    {
        [JsonPropertyName("id")]
        public int? Id { get; set; }
        [JsonPropertyName("customerId")]
        public int? CustomerId { get; set; }
        [JsonPropertyName("shippingAddressId")]
        public int? ShippingAddressId { get; set; }
        [JsonPropertyName("status")]
        public string? Status { get; set; }
        [JsonPropertyName("placedAt")]
        public DateTime? PlacedAt { get; set; }
    }

    public class Customer
    {
        [JsonPropertyName("id")]
        public int? Id { get; set; }
        [JsonPropertyName("name")]
        public string? Name { get; set; }
    }

    public class Address
    {
        [JsonPropertyName("id")]
        public int? Id { get; set; }
        [JsonPropertyName("street")]
        public string? Street { get; set; }
        [JsonPropertyName("zip")]
        public string? Zip { get; set; }
        [JsonPropertyName("city")]
        public string? City { get; set; }
    }

    /// <summary>An opaque alias placeholder (the "@alias" wire value) produced by
    /// <see cref="BatchEntry.Alias"/>. Implicitly converts into any <see cref="Arg{T}"/>,
    /// so a consumer param accepts <c>order.Alias("@customerId")</c>.</summary>
    public readonly struct Alias
    {
        /// <summary>The wire placeholder string, including the leading '@'.</summary>
        public string Placeholder { get; }
        public Alias(string placeholder) => Placeholder = placeholder;
    }

    /// <summary>A typed method argument that accepts either a literal value of <typeparamref name="T"/>
    /// or an <see cref="Alias"/> from a producer's <see cref="BatchEntry.Alias"/>. This is the
    /// C# analogue of the TS typed-batch: <c>GetById(Arg&lt;int&gt; id)</c> accepts <c>42</c> and
    /// <c>order.Alias("@customerId")</c> but rejects <c>"oops"</c>. The alias→param-type match is
    /// checked at runtime (Roslyn source-generator compile-time check is a future increment).</summary>
    public readonly struct Arg<T>
    {
        private readonly object? _value;
        private Arg(object? value) => _value = value;

        public static implicit operator Arg<T>(T value) => new(value);
        public static implicit operator Arg<T>(Alias alias) => new(alias);

        /// <summary>The wire value: the literal, or the "@alias" placeholder string for an alias.</summary>
        internal object? ToWireValue() => _value is Alias a ? a.Placeholder : _value;
    }


    /// <summary>A single Sleipnir call built from a generated controller method. Pass to
    /// <see cref="SleipnirClient.Call{T}"/> for a single typed call, or to <see cref="Batch.Add"/>
    /// to enroll it in a dependency-chained batch.</summary>
    public sealed class Call
    {
        private readonly SleipnirCall _call;
        internal Call(SleipnirCall call) => _call = call;

        /// <summary>Declare that this call exposes <paramref name="jsonPath"/> as <paramref name="alias"/>.
        /// The wire <c>dependencyMapping</c> key is the alias WITHOUT the leading '@' (the server
        /// strips '@' from a consumer's '@alias' placeholder before lookup), so we strip it here.</summary>
        public Call Exposes(string jsonPath, string alias)
        {
            _call.Exposes(jsonPath, alias.StartsWith('@') ? alias.Substring(1) : alias);
            return this;
        }

        /// <summary>Set the request id (correlation; used by SleipnirMultiCallResponse.Get{T}).</summary>
        public Call Named(string id)
        {
            _call.Named(id);
            return this;
        }

        internal SleipnirRequest ToRequest() => _call.ToRequest();
    }

    /// <summary>A call enrolled in a batch. <see cref="Exposes"/> declares an alias the server
    /// resolves from this call's result; <see cref="Alias"/> yields the typed placeholder for a
    /// consumer parameter.</summary>
    public sealed class BatchEntry
    {
        private readonly Call _call;
        internal BatchEntry(Call call) => _call = call;

        public BatchEntry Exposes(string jsonPath, string alias)
        {
            _call.Exposes(jsonPath, alias);
            return this;
        }

        /// <summary>Resolve a previously-declared alias to its placeholder (for a consumer param).
        /// Returns the "@alias" wire value; <c>Arg&lt;T&gt;</c> converts it implicitly.
        /// '@'-normalization is symmetric with <see cref="Exposes"/>: Exposes strips a
        /// leading '@' (the wire dependencyMapping key is the bare name — the server
        /// strips the consumer's '@alias' placeholder before lookup), while Alias
        /// ENSURES a leading '@' (the consumer sends the "@alias" placeholder). So
        /// both call styles work: Alias("ids") → "@ids" and Alias("@ids") → "@ids".
        /// Returning the bare name (the 1.2.1 bug) sent "ids" on the wire, which the
        /// server's ReplaceDependencyByAlias never matched.</summary>
        public Alias Alias(string name) => new(name.StartsWith('@') ? name : "@" + name);
    }

    /// <summary>Batch builder for dependency-chained calls. Execution mode is Serial (the only
    /// mode that resolves '@alias' placeholders). Add calls in topological order: a producer's
    /// <see cref="BatchEntry.Exposes"/> must run before any consumer's <see cref="BatchEntry.Alias"/>.</summary>
    public sealed class Batch
    {
        private readonly List<Call> _calls = new();

        public BatchEntry Add(Call call)
        {
            _calls.Add(call);
            return new BatchEntry(call);
        }

        internal SleipnirMultiRequest ToMulti() => new()
        {
            Requests = _calls.Select(c => c.ToRequest()).ToList(),
            Mode = ExecutionMode.Serial,
        };
    }


    public sealed class StockClient
    {
        public Call GetByArticles(Arg<List<int>> articleIds) => new Call(SleipnirCall.Init("Stock", "GetByArticles").Param("articleIds", articleIds.ToWireValue()));
    }

    public sealed class OrderLineClient
    {
        public Call GetByOrder(Arg<int> orderId) => new Call(SleipnirCall.Init("OrderLine", "GetByOrder").Param("orderId", orderId.ToWireValue()));
    }

    public sealed class ArticleClient
    {
        public Call GetByIds(Arg<List<int>> articleIds) => new Call(SleipnirCall.Init("Article", "GetByIds").Param("articleIds", articleIds.ToWireValue()));
    }

    public sealed class OrderClient
    {
        public Call GetById(Arg<int> id) => new Call(SleipnirCall.Init("Order", "GetById").Param("id", id.ToWireValue()));
    }

    public sealed class CustomerClient
    {
        public Call GetById(Arg<int> customerId) => new Call(SleipnirCall.Init("Customer", "GetById").Param("customerId", customerId.ToWireValue()));
    }

    public sealed class AddressClient
    {
        public Call GetById(Arg<int> addressId) => new Call(SleipnirCall.Init("Address", "GetById").Param("addressId", addressId.ToWireValue()));
    }

    /// <summary>Root generated Sleipnir client. Wraps an <see cref="ISleipnirClient"/> (a
    /// <see cref="SleipnirRestJsonClient"/> by default) and exposes one accessor per controller.
    /// Use <see cref="Call{T}"/> for a single typed call, <see cref="Batch"/> for a dependency chain.
    /// Named SleipnirGeneratedClient to avoid colliding with the global SleipnirClient namespace.</summary>
    public sealed class SleipnirGeneratedClient
    {
        private readonly ISleipnirClient _client;

        public SleipnirGeneratedClient(string baseUrl) : this(new SleipnirRestJsonClient(baseUrl)) { }

        public SleipnirGeneratedClient(ISleipnirClient client) => _client = client;

        public StockClient Stock { get; } = new();
        public OrderLineClient OrderLine { get; } = new();
        public ArticleClient Article { get; } = new();
        public OrderClient Order { get; } = new();
        public CustomerClient Customer { get; } = new();
        public AddressClient Address { get; } = new();

        /// <summary>Execute a single typed call; the result is deserialized into T.</summary>
        public Task<T?> Call<T>(Call call) => _client.Call<T>(call.ToRequest());

        /// <summary>Execute a typed batch (Serial — required for @alias resolution). Results are
        /// fetched by request id via <see cref="SleipnirMultiCallResponse.Get{T}"/>.</summary>
        public Task<SleipnirMultiCallResponse> Batch(Batch batch) =>
            SleipnirMultiCallResponse.Call(_client, batch.ToMulti());
    }
}
