// <auto-generated> Sleipnir LINQ contracts — generated by sleipnir-linq. Do not edit.
// Generated from Sleipnir runtime discovery. The interfaces ARE the contract.
// Requires the Sleipnir.Client.Linq NuGet package (Arg<T>, Dep<T>,
// [SleipnirServiceContract], [SleipnirMethodContract], [SleipnirNavigation]).
// DTO properties are camelCase on the wire; [JsonPropertyName] maps them to PascalCase POCOs.
// [SleipnirNavigation] edges are emitted from the server-side [SleipnirNavigation] through
// discovery and drift-checked at generation time (fetch/key/param validated by EmitContracts).
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Sleipnir.Client.Linq;

namespace Sleipnir.Guide.Admin.Linq
{
    public class Holding
    {
        [JsonPropertyName("symbol")]
        public string? Symbol { get; set; }
        [JsonPropertyName("quantity")]
        public decimal? Quantity { get; set; }
        [JsonPropertyName("averagePrice")]
        public decimal? AveragePrice { get; set; }
    }

    public class Order
    {
        [JsonPropertyName("id")]
        public int? Id { get; set; }
        [JsonPropertyName("symbol")]
        public string? Symbol { get; set; }
        [JsonPropertyName("quantity")]
        public decimal? Quantity { get; set; }
        [JsonPropertyName("price")]
        public decimal? Price { get; set; }
        [JsonPropertyName("time")]
        public DateTime? Time { get; set; }
    }

    public class Profile
    {
        [JsonPropertyName("username")]
        public string? Username { get; set; }
        [JsonPropertyName("role")]
        public string? Role { get; set; }
    }

    public class Quote
    {
        [JsonPropertyName("symbol")]
        public string? Symbol { get; set; }
        [JsonPropertyName("price")]
        public decimal? Price { get; set; }
        [JsonPropertyName("change")]
        public decimal? Change { get; set; }
        [JsonPropertyName("time")]
        public DateTime? Time { get; set; }
    }

    [SleipnirServiceContract("Account")]
    public interface IAccountService
    {
        /// <summary>Exchange username + password for a JWT bearer token. Try customer/customer or admin/admin. The token is sent back as Authorization: Bearer on subsequent calls.</summary>
        // TODO: return type "SleipnirResponse" is an opaque framework/BCL type not modelled in discovery; deserialize as object.
        [SleipnirMethodContract("Login")]
        Task<object?> Login(Arg<string> username, Arg<string> password);

        /// <summary>Return the caller's profile from the bearer token. Requires authentication (any role).</summary>
        [SleipnirMethodContract("Me")]
        Task<Profile?> Me();
    }

    [SleipnirServiceContract("Market")]
    public interface IMarketService
    {
        /// <summary>Get a snapshot price quote for a single market symbol. Returns null if the symbol is unknown.</summary>
        [SleipnirMethodContract("GetQuote")]
        Task<Quote?> GetQuote(Arg<string> symbol);

        /// <summary>Bulk-fetch quotes for many symbols in one call. Unknown symbols are skipped. For composing arbitrary methods in one roundtrip, prefer a SleipnirMultiRequest batch (chapter 5).</summary>
        [SleipnirMethodContract("GetQuotes")]
        Task<List<Quote>?> GetQuotes(Arg<List<string>> symbols);

        /// <summary>Find symbols whose ticker or full name contains the query (case-insensitive). Returns the matching tickers — the chain provider for GetQuotes(@symbols): Search exposes $[*] as 'symbols', GetQuotes consumes @symbols, one roundtrip.</summary>
        [SleipnirMethodContract("Search")]
        Task<List<string>?> Search(Arg<string> query);
    }

    [SleipnirServiceContract("Portfolio")]
    public interface IPortfolioService
    {
        /// <summary>Return the caller's portfolio holdings. Requires authentication (any role).</summary>
        [SleipnirMethodContract("GetHoldings")]
        Task<List<Holding>?> GetHoldings();

        /// <summary>Place a market order for a symbol + quantity. Returns the filled Order. Chain provider for GetOrder(@orderId): expose $.Id as 'orderId'.</summary>
        [SleipnirMethodContract("PlaceOrder")]
        Task<Order?> PlaceOrder(Arg<string> symbol, Arg<decimal> quantity);

        /// <summary>Fetch a previously placed order by id. Chain consumer: PlaceOrder exposes $.Id as 'orderId', GetOrder(@orderId) resolves it.</summary>
        // TODO: return type "SleipnirResponse" is an opaque framework/BCL type not modelled in discovery; deserialize as object.
        [SleipnirMethodContract("GetOrder")]
        Task<object?> GetOrder(Arg<int> id);

        /// <summary>Start the live price feed (chapter 9). Admin role required — a Customer token gets 403.</summary>
        [SleipnirMethodContract("StartFeed")]
        Task<bool?> StartFeed();

        /// <summary>Stop the live price feed (chapter 9). Admin role required — a Customer token gets 403.</summary>
        [SleipnirMethodContract("StopFeed")]
        Task<bool?> StopFeed();
    }

}
