// C# LINQ-contract emitter — emits a single SleipnirContracts.g.cs containing the POCO DTOs and the
// [SleipnirServiceContract] service interfaces consumed by Sleipnir.Client.Linq (SleipnirLinqClient).
// This is a second emission mode of the core: it reuses the SAME EmitterBuilder / NamingResolver /
// Casing / Scalars / DiscoveryShape pipeline as CsEmitter (so it handles the real TypeRef IR —
// scalar/array/set/map/stream/ref/opaque/void — not flat type strings). CsEmitter / EmitClient and the
// parity gate are untouched; this emitter has no TS counterpart (interfaces with attributes are C#-only).
using System;
using System.Collections.Generic;
using System.Text;

namespace Sleipnir.Codegen.Core;

internal static class CsContractsEmitter
{
    private const string AutoGeneratedHeader =
        "// <auto-generated> Sleipnir LINQ contracts — generated by sleipnir-linq. Do not edit.";

    private static readonly string[] HeaderLines =
    {
        "// Generated from Sleipnir runtime discovery. The interfaces ARE the contract.",
        "// Requires the Sleipnir.Client.Linq NuGet package (Arg<T>, Dep<T>,",
        "// [SleipnirServiceContract], [SleipnirMethodContract]).",
        "// DTO properties are camelCase on the wire; [JsonPropertyName] maps them to PascalCase POCOs.",
    };

    /// <summary>Emit the C# LINQ contracts as a single SleipnirContracts.g.cs string.</summary>
    public static string Emit(EmitterInput input, EmitCsOptions opts)
    {
        var ns = string.IsNullOrEmpty(opts.Namespace) ? "Sleipnir.Linq.Contracts" : opts.Namespace!;
        // One shared resolver (mirrors CsEmitter.Emit's resolverFor): registered with every type full
        // name, used for both POCO property ref types and method param/return ref types.
        var resolver = new NamingResolver();
        foreach (var t in input.Types) resolver.Register(t.FullName);

        var sb = new StringBuilder();
        sb.Append(AutoGeneratedHeader).Append('\n');
        sb.Append(string.Join("\n", HeaderLines));
        if (!string.IsNullOrEmpty(opts.BaseUrl))
            sb.Append('\n').Append("// Discovery base URL: ").Append(opts.BaseUrl);
        sb.Append('\n');
        sb.Append("#nullable enable\n");
        sb.Append("using System;\n");
        sb.Append("using System.Collections.Generic;\n");
        sb.Append("using System.Text.Json.Serialization;\n");
        sb.Append("using System.Threading.Tasks;\n");
        sb.Append("using Sleipnir.Client.Linq;\n\n");
        sb.Append("namespace ").Append(ns).Append("\n{\n");

        sb.Append(EmitPocos(input.Types, resolver));
        sb.Append('\n');

        sb.Append(EmitInterfaces(input.Controllers, resolver));
        sb.Append("\n"); // trailing newline before namespace close

        sb.Append("}\n"); // namespace close + trailing newline
        return sb.ToString();
    }

    // --- POCOs — mirrored from CsEmitter (nullable props, [JsonPropertyName] wire). Kept inline rather
    //     than shared so CsEmitter / the parity gate stay untouched. ---

    private static string EmitPocos(List<ResolvedType> types, NamingResolver resolver)
    {
        if (types.Count == 0) return "    // No structured types declared in discovery.\n";
        var blocks = new List<string>(types.Count);
        foreach (var t in types) blocks.Add(EmitPoco(t, resolver));
        return string.Join("\n\n", blocks) + "\n";
    }

    private static string EmitPoco(ResolvedType t, NamingResolver resolver)
    {
        var props = new List<string>(t.Properties.Count);
        foreach (var p in t.Properties) props.Add(EmitPocoProperty(p, resolver));
        return "    public class " + t.EmittedName + "\n    {\n" + string.Join("\n", props) + "\n    }";
    }

    private static string EmitPocoProperty(ResolvedProperty p, NamingResolver resolver)
    {
        var ty = EmitterBuilder.Nullable(EmitterBuilder.CsTypeOfRef(p.TypeRef, resolver));
        var propName = Casing.PascalCase(p.DeclaredName);
        var todo = p.TypeRef.Kind == "opaque"
            ? "        // TODO: property \"" + p.DeclaredName + "\" type \"" + (p.TypeRef.NativeName ?? "?") + "\" is an opaque framework/BCL type not modelled in discovery; emitted as object.\n"
            : "";
        var doc = !string.IsNullOrEmpty(p.Documentation) ? "        /// <summary>" + p.Documentation + "</summary>\n" : "";
        return doc + todo + "        [JsonPropertyName(\"" + p.WireName + "\")]\n        public " + ty + " " + propName + " { get; set; }";
    }

    // --- Service interfaces — one [SleipnirServiceContract] interface per controller. ---

    private static string EmitInterfaces(List<ResolvedController> controllers, NamingResolver resolver)
    {
        if (controllers.Count == 0) return "    // No controllers declared in discovery.\n";
        var blocks = new List<string>(controllers.Count);
        foreach (var c in controllers) blocks.Add(EmitInterface(c, resolver));
        return string.Join("\n\n", blocks) + "\n";
    }

    private static string EmitInterface(ResolvedController c, NamingResolver resolver)
    {
        var methods = new List<string>(c.Methods.Count);
        foreach (var m in c.Methods) methods.Add(EmitInterfaceMethod(m, resolver));
        return "    [SleipnirServiceContract(\"" + c.Name + "\")]\n    public interface I" + c.Name + "Service\n    {\n" + string.Join("\n\n", methods) + "\n    }";
    }

    private static string EmitInterfaceMethod(ResolvedMethod m, NamingResolver resolver)
    {
        var parms = new List<string>(m.Parameters.Count);
        foreach (var p in m.Parameters)
            parms.Add("Arg<" + EmitterBuilder.CsTypeOfRef(p.TypeRef, resolver) + "> " + p.Name);
        var doc = !string.IsNullOrEmpty(m.Documentation) ? "        /// <summary>" + m.Documentation + "</summary>\n" : "";

        // Event returns (IObservable<T>, Phase 3) are not supported by the SleipnirLinqClient lambda
        // surface in Tier 1 — emit a TODO and a void-Task signature so the interface still compiles.
        if (m.ReturnType.Kind == "event")
        {
            return doc + "        // TODO: return kind \"event\" (IObservable<T>) is not supported by Sleipnir.Client.Linq in Tier 1.\n" +
                   "        [SleipnirMethodContract(\"" + m.MethodName + "\")]\n        Task " + m.MethodName + "(" + string.Join(", ", parms) + ");";
        }

        var ret = m.IsVoid
            ? "Task"
            : "Task<" + EmitterBuilder.Nullable(EmitterBuilder.CsTypeOfRef(m.ReturnType, resolver)) + ">";
        var todo = (m.ReturnType.Kind == "opaque" && !m.IsVoid)
            ? "        // TODO: return type \"" + (m.ReturnType.NativeName ?? "?") + "\" is an opaque framework/BCL type not modelled in discovery; deserialize as object.\n"
            : "";
        return doc + todo + "        [SleipnirMethodContract(\"" + m.MethodName + "\")]\n        " + ret + " " + m.MethodName + "(" + string.Join(", ", parms) + ");";
    }
}