// C# emitter — emits a single SleipnirGenerated.cs that calls into the real C# SleipnirClient
// runtime (SleipnirCall / SleipnirRestJsonClient / ISleipnirClient.Call<T> / SleipnirMultiCallResponse).
// Ported from clients/codegen/src/emitters/cs.ts. The static runtime blocks (Alias, Arg,
// Call, Batch, the root client preamble/footer) are reproduced verbatim from the committed
// snapshot (clients/codegen/test/snapshots/story01.cs/SleipnirGenerated.cs) as line arrays joined
// by "\n", so the output is byte-for-byte equal to the TS --lang cs emitter — the parity gate
// (CsCodegenParityTests) asserts exactly that. The dynamic parts are the POCOs, the
// per-controller method classes, and the root accessors, assembled from the resolved input.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Sleipnir.Codegen.Core;

internal static class CsEmitter
{
    private const string AutoGeneratedHeader =
        "// <auto-generated> Sleipnir client stub — generated by sleipnir-gen (--lang cs). Do not edit.";

    private static readonly string[] HeaderLines =
    {
        "// Generated from Sleipnir runtime discovery. The C# classes ARE the contract.",
        "// Properties are camelCase on the wire; [JsonPropertyName] maps them to PascalCase POCOs.",
        "// Requires the SleipnirClient NuGet package (SleipnirCall, SleipnirTransportRouter, ISleipnirClient).",
        "// The root client is named SleipnirGeneratedClient (not SleipnirClient) to avoid a collision",
        "// with the global SleipnirClient namespace (the runtime's SleipnirClient.Sleipnir).",
    };

    /// <summary>The capability literal baked into the header + root ctor (lowercase for comments).</summary>
    private static string CapabilityLiteral(EmitCsOptions opts)
        => string.IsNullOrEmpty(opts.Capability) ? "all" : opts.Capability!;

    /// <summary>The enum member for the root ctor (PascalCase: "all" → "All").</summary>
    private static string CapabilityEnum(EmitCsOptions opts)
    {
        var cap = CapabilityLiteral(opts);
        return "SleipnirBundleCapability." + char.ToUpperInvariant(cap[0]) + cap.Substring(1);
    }

    private static string[] CapabilityHeaderLines(EmitCsOptions opts)
    {
        var cap = CapabilityLiteral(opts);
        return new[]
        {
            "// Transport capability: --transport " + cap + ". The (string baseUrl) ctor wraps a",
            "// SleipnirTransportRouter with this capability; pass a custom ISleipnirClient to override.",
            "// defaultTransport=auto: WebSocket probed first, falls back to REST+SSE on failure.",
        };
    }

    // Alias + Arg<T> — the typed-alias bridge for batch dependency chains.
    private static readonly string[] AliasLines =
    {
        "    /// <summary>An opaque alias placeholder (the \"@alias\" wire value) produced by",
        "    /// <see cref=\"BatchEntry.Alias\"/>. Implicitly converts into any <see cref=\"Arg{T}\"/>,",
        "    /// so a consumer param accepts <c>order.Alias(\"@customerId\")</c>.</summary>",
        "    public readonly struct Alias",
        "    {",
        "        /// <summary>The wire placeholder string, including the leading '@'.</summary>",
        "        public string Placeholder { get; }",
        "        public Alias(string placeholder) => Placeholder = placeholder;",
        "    }",
        "",
        "    /// <summary>A typed method argument that accepts either a literal value of <typeparamref name=\"T\"/>",
        "    /// or an <see cref=\"Alias\"/> from a producer's <see cref=\"BatchEntry.Alias\"/>. This is the",
        "    /// C# analogue of the TS typed-batch: <c>GetById(Arg&lt;int&gt; id)</c> accepts <c>42</c> and",
        "    /// <c>order.Alias(\"@customerId\")</c> but rejects <c>\"oops\"</c>. The alias→param-type match is",
        "    /// checked at runtime (Roslyn source-generator compile-time check is a future increment).</summary>",
        "    public readonly struct Arg<T>",
        "    {",
        "        private readonly object? _value;",
        "        private Arg(object? value) => _value = value;",
        "",
        "        public static implicit operator Arg<T>(T value) => new(value);",
        "        public static implicit operator Arg<T>(Alias alias) => new(alias);",
        "",
        "        /// <summary>The wire value: the literal, or the \"@alias\" placeholder string for an alias.</summary>",
        "        internal object? ToWireValue() => _value is Alias a ? a.Placeholder : _value;",
        "    }",
    };

    // Call + BatchEntry + Batch — the batch builder (mirrors the TS runtime).
    private static readonly string[] CallLines =
    {
        "    /// <summary>A single Sleipnir call built from a generated controller method. Pass to",
        "    /// <see cref=\"SleipnirClient.Call{T}\"/> for a single typed call, or to <see cref=\"Batch.Add\"/>",
        "    /// to enroll it in a dependency-chained batch.</summary>",
        "    public sealed class Call",
        "    {",
        "        private readonly SleipnirCall _call;",
        "        internal Call(SleipnirCall call) => _call = call;",
        "",
        "        /// <summary>Declare that this call exposes <paramref name=\"jsonPath\"/> as <paramref name=\"alias\"/>.",
        "        /// The wire <c>dependencyMapping</c> key is the alias WITHOUT the leading '@' (the server",
        "        /// strips '@' from a consumer's '@alias' placeholder before lookup), so we strip it here.</summary>",
        "        public Call Exposes(string jsonPath, string alias)",
        "        {",
        "            _call.Exposes(jsonPath, alias.StartsWith('@') ? alias.Substring(1) : alias);",
        "            return this;",
        "        }",
        "",
        "        /// <summary>Set the request id (correlation; used by SleipnirMultiCallResponse.Get{T}).</summary>",
        "        public Call Named(string id)",
        "        {",
        "            _call.Named(id);",
        "            return this;",
        "        }",
        "",
        "        internal SleipnirRequest ToRequest() => _call.ToRequest();",
        "    }",
        "",
        "    /// <summary>A call enrolled in a batch. <see cref=\"Exposes\"/> declares an alias the server",
        "    /// resolves from this call's result; <see cref=\"Alias\"/> yields the typed placeholder for a",
        "    /// consumer parameter.</summary>",
        "    public sealed class BatchEntry",
        "    {",
        "        private readonly Call _call;",
        "        internal BatchEntry(Call call) => _call = call;",
        "",
        "        public BatchEntry Exposes(string jsonPath, string alias)",
        "        {",
        "            _call.Exposes(jsonPath, alias);",
        "            return this;",
        "        }",
        "",
        "        /// <summary>Resolve a previously-declared alias to its placeholder (for a consumer param).",
        "        /// Returns the \"@alias\" wire value; <c>Arg&lt;T&gt;</c> converts it implicitly.",
        "        /// '@'-normalization is symmetric with <see cref=\"Exposes\"/>: Exposes strips a",
        "        /// leading '@' (the wire dependencyMapping key is the bare name — the server",
        "        /// strips the consumer's '@alias' placeholder before lookup), while Alias",
        "        /// ENSURES a leading '@' (the consumer sends the \"@alias\" placeholder). So",
        "        /// both call styles work: Alias(\"ids\") → \"@ids\" and Alias(\"@ids\") → \"@ids\".",
        "        /// Returning the bare name (the 1.2.1 bug) sent \"ids\" on the wire, which the",
        "        /// server's ReplaceDependencyByAlias never matched.</summary>",
        "        public Alias Alias(string name) => new(name.StartsWith('@') ? name : \"@\" + name);",
        "    }",
        "",
        "    /// <summary>Batch builder for dependency-chained calls. Execution mode is Serial (the only",
        "    /// mode that resolves '@alias' placeholders). Add calls in topological order: a producer's",
        "    /// <see cref=\"BatchEntry.Exposes\"/> must run before any consumer's <see cref=\"BatchEntry.Alias\"/>.</summary>",
        "    public sealed class Batch",
        "    {",
        "        private readonly List<Call> _calls = new();",
        "",
        "        public BatchEntry Add(Call call)",
        "        {",
        "            _calls.Add(call);",
        "            return new BatchEntry(call);",
        "        }",
        "",
        "        internal SleipnirMultiRequest ToMulti() => new()",
        "        {",
        "            Requests = _calls.Select(c => c.ToRequest()).ToList(),",
        "            Mode = ExecutionMode.Serial,",
        "        };",
        "    }",
    };

    // Root SleipnirGeneratedClient — preamble (before accessors) and footer (after accessors).
    private static string[] RootPreambleLines(EmitCsOptions opts)
    {
        var cap = CapabilityLiteral(opts);
        return new[]
        {
        "    /// <summary>Root generated Sleipnir client. Wraps an <see cref=\"ISleipnirClient\"/> — a",
        "    /// <see cref=\"SleipnirTransportRouter\"/> by default, which bundles the backends selected by the",
        "    /// codegen <c>--transport " + cap + "</c> capability and routes calls to the active call backend",
        "    /// and subscriptions to the active event backend. Exposes one accessor per controller. Use",
        "    /// <see cref=\"Call{T}\"/> for a single typed call, <see cref=\"Subscribe{T}\"/> for a server-push",
        "    /// event, <see cref=\"Batch\"/> for a dependency chain. Named SleipnirGeneratedClient to avoid",
        "    /// colliding with the global SleipnirClient namespace.</summary>",
        "    public sealed class SleipnirGeneratedClient",
        "    {",
        "        private readonly ISleipnirClient _client;",
        "",
        "        /// <summary>Construct with a <see cref=\"SleipnirTransportRouter\"/> bundling the codegen",
        "        /// capability (<c>" + cap + "</c>); defaultTransport=auto (WebSocket → REST+SSE fallback).</summary>",
        "        public SleipnirGeneratedClient(string baseUrl) : this(new SleipnirTransportRouter(",
        "            new SleipnirRouterOptions { BaseUrl = baseUrl, Capability = " + CapabilityEnum(opts) + " })) { }",
        "",
        "        /// <summary>Construct with a custom <see cref=\"ISleipnirClient\"/> (e.g. a pre-configured",
        "        /// <see cref=\"SleipnirTransportRouter\"/>, a specific backend, or <c>SleipnirInMemoryClient</c>",
        "        /// for tests).</summary>",
        "        public SleipnirGeneratedClient(ISleipnirClient client) => _client = client;",
        };
    }

    private static readonly string[] RootFooterLines =
    {
        "        /// <summary>The underlying client — cast to <see cref=\"SleipnirTransportRouter\"/> to access",
        "        /// <c>NegotiateAsync</c>/<c>UseTransportAsync</c> and the raw backend escape hatches.</summary>",
        "        public ISleipnirClient Client => _client;",
        "",
        "        /// <summary>Execute a single typed call; the result is deserialized into T.</summary>",
        "        public Task<T?> Call<T>(Call call) => _client.Call<T>(call.ToRequest());",
        "",
        "        /// <summary>Subscribe to a server-push event (a <see cref=\"Call\"/> built from an",
        "        /// <c>[SleipnirEvent]</c> method). Routes to the active event backend (WebSocket / SSE /",
        "        /// SignalR, per the transport profile). Returns a hot <see cref=\"SleipnirSubscription{T}\"/>",
        "        /// (IObservable + IDisposable); dispose to unsubscribe. <paramref name=\"resumePolicy\"/>",
        "        /// governs cross-transport resume on disconnect.</summary>",
        "        public Task<SleipnirSubscription<T>> Subscribe<T>(Call call, ResumePolicy? resumePolicy = null, CancellationToken ct = default)",
        "            => _client.SubscribeAsync<T>(call.ToRequest(), resumePolicy, ct);",
        "",
        "        /// <summary>Execute a typed batch (Serial — required for @alias resolution). Results are",
        "        /// fetched by request id via <see cref=\"SleipnirMultiCallResponse.Get{T}\"/>.</summary>",
        "        public Task<SleipnirMultiCallResponse> Batch(Batch batch) =>",
        "            SleipnirMultiCallResponse.Call(_client, batch.ToMulti());",
        "    }",
    };

    /// <summary>Emit the C# client as a single SleipnirGenerated.cs string.</summary>
    public static string Emit(EmitterInput input, EmitCsOptions opts)
    {
        var ns = string.IsNullOrEmpty(opts.Namespace) ? "Sleipnir.Generated" : opts.Namespace!;
        // One shared resolver (mirrors the TS emitter's resolverFor): registered with every type
        // full name, used for both POCO property ref types and method param ref types.
        var resolver = new NamingResolver();
        foreach (var t in input.Types) resolver.Register(t.FullName);

        var sb = new StringBuilder();
        sb.Append(AutoGeneratedHeader).Append('\n');
        sb.Append(string.Join("\n", HeaderLines));
        sb.Append('\n').Append(string.Join("\n", CapabilityHeaderLines(opts)));
        if (!string.IsNullOrEmpty(opts.BaseUrl))
            sb.Append('\n').Append("// Discovery base URL: ").Append(opts.BaseUrl);
        sb.Append('\n');
        sb.Append("#nullable enable\n");
        sb.Append("using System;\n");
        sb.Append("using System.Collections.Generic;\n");
        sb.Append("using System.Linq;\n");
        sb.Append("using System.Text.Json.Serialization;\n");
        sb.Append("using System.Threading;\n");
        sb.Append("using System.Threading.Tasks;\n");
        sb.Append("using SleipnirClient.Sleipnir;\n");
        sb.Append("using SleipnirCommon.Models;\n\n");
        sb.Append("namespace ").Append(ns).Append("\n{\n");

        sb.Append(EmitPocos(input.Types, resolver));
        sb.Append('\n'); // template newline after ${pocos}

        sb.Append(string.Join("\n", AliasLines)).Append("\n\n"); // alias block ends "    }\n\n"
        sb.Append('\n'); // template newline after ${alias}

        sb.Append(string.Join("\n", CallLines)).Append("\n\n"); // call block ends "    }\n\n"
        sb.Append('\n'); // template newline after ${call}

        sb.Append(EmitControllers(input.Controllers, resolver));
        sb.Append("\n\n"); // template "\n\n" between controllers and root

        sb.Append(EmitRootClient(input.Controllers, opts));

        sb.Append("\n}\n"); // namespace close + trailing newline
        return sb.ToString();
    }

    private static string EmitPocos(List<ResolvedType> types, NamingResolver resolver)
    {
        if (types.Count == 0) return "    // No structured types declared in discovery.\n";
        var blocks = new List<string>(types.Count);
        foreach (var t in types) blocks.Add(EmitPoco(t, resolver));
        return string.Join("\n\n", blocks) + "\n";
    }

    private static string EmitPoco(ResolvedType t, NamingResolver resolver)
    {
        var props = new List<string>(t.Properties.Count);
        foreach (var p in t.Properties) props.Add(EmitPocoProperty(p, resolver));
        return "    public class " + t.EmittedName + "\n    {\n" + string.Join("\n", props) + "\n    }";
    }

    private static string EmitPocoProperty(ResolvedProperty p, NamingResolver resolver)
    {
        var ty = EmitterBuilder.Nullable(EmitterBuilder.CsTypeOfRef(p.TypeRef, resolver));
        var propName = Casing.PascalCase(p.DeclaredName);
        var todo = p.TypeRef.Kind == "opaque"
            ? "        // TODO: property \"" + p.DeclaredName + "\" type \"" + (p.TypeRef.NativeName ?? "?") + "\" is an opaque framework/BCL type not modelled in discovery; emitted as object.\n"
            : "";
        var doc = !string.IsNullOrEmpty(p.Documentation) ? "        /// <summary>" + p.Documentation + "</summary>\n" : "";
        return doc + todo + "        [JsonPropertyName(\"" + p.WireName + "\")]\n        public " + ty + " " + propName + " { get; set; }";
    }

    private static string EmitControllers(List<ResolvedController> controllers, NamingResolver resolver)
    {
        if (controllers.Count == 0) return "";
        var blocks = new List<string>(controllers.Count);
        foreach (var c in controllers) blocks.Add(EmitControllerClass(c, resolver));
        return string.Join("\n\n", blocks);
    }

    private static string EmitControllerClass(ResolvedController c, NamingResolver resolver)
    {
        var methods = new List<string>(c.Methods.Count);
        foreach (var m in c.Methods) methods.Add(EmitMethod(c, m, resolver));
        return "    public sealed class " + c.ClassName + "\n    {\n" + string.Join("\n\n", methods) + "\n    }";
    }

    private static string EmitMethod(ResolvedController ctrl, ResolvedMethod m, NamingResolver resolver)
    {
        var doc = !string.IsNullOrEmpty(m.Documentation) ? "        /// <summary>" + m.Documentation + "</summary>\n" : "";
        var todo = (m.ReturnType.Kind == "opaque" && !m.IsVoid)
            ? "        // TODO: return type \"" + (m.ReturnType.NativeName ?? "?") + "\" is an opaque framework/BCL type not modelled in discovery; deserialize as object.\n"
            : "";

        // Phase 4 unified transport: event methods ([SleipnirEvent] → IObservable<T>) build the
        // SAME Call as a regular method — the request (controller/method/params) is identical; only
        // the execution entry point differs (Subscribe<T> on the root vs Call<T>). The active event
        // backend (WS / SSE / SignalR, per the transport profile) is chosen by the router, so the
        // generated stub stays transport-agnostic.
        if (m.ReturnType.Kind == "event" && m.ReturnType.Element != null)
        {
            var elementType = EmitterBuilder.CsTypeOfRef(m.ReturnType.Element, resolver);
            var argParms = new List<string>(m.Parameters.Count);
            foreach (var p in m.Parameters)
                argParms.Add("Arg<" + EmitterBuilder.CsTypeOfRef(p.TypeRef, resolver) + "> " + p.Name);
            var argParamChain = new StringBuilder();
            foreach (var p in m.Parameters)
                argParamChain.Append(".Param(\"" + p.Name + "\", " + p.Name + ".ToWireValue())");
            var remarks = "        /// <remarks>" + m.MethodName + " is a [SleipnirEvent] (server-push, IObservable&lt;" + elementType + "&gt;).\n" +
                          "        /// Build the call, then subscribe via <see cref=\"SleipnirGeneratedClient.Subscribe{T}\"/> (routes to the\n" +
                          "        /// active event backend — WebSocket / SSE / SignalR depending on the transport profile).</remarks>\n";
            return doc + remarks + "        public Call " + m.MethodName + "(" + string.Join(", ", argParms) + ") => new Call(SleipnirCall.Init(\"" + ctrl.Name + "\", \"" + m.MethodName + "\")" + argParamChain + ");";
        }

        // Call-Methoden (bestehend): Arg<T>-Wrapper für Dependency-Chaining.
        var argParms2 = new List<string>(m.Parameters.Count);
        foreach (var p in m.Parameters)
            argParms2.Add("Arg<" + EmitterBuilder.CsTypeOfRef(p.TypeRef, resolver) + "> " + p.Name);
        var argParamChain2 = new StringBuilder();
        foreach (var p in m.Parameters)
            argParamChain2.Append(".Param(\"" + p.Name + "\", " + p.Name + ".ToWireValue())");
        return doc + todo + "        public Call " + m.MethodName + "(" + string.Join(", ", argParms2) + ") => new Call(SleipnirCall.Init(\"" + ctrl.Name + "\", \"" + m.MethodName + "\")" + argParamChain2 + ");";
    }

    private static string EmitRootClient(List<ResolvedController> controllers, EmitCsOptions opts)
    {
        var accessors = controllers.Select(c => "        public " + c.ClassName + " " + c.Name + " { get; } = new();");
        return string.Join("\n", RootPreambleLines(opts)) + "\n\n" + string.Join("\n", accessors) + "\n\n" + string.Join("\n", RootFooterLines);
    }
}