// C# emitter — emits a single TrameGenerated.cs that calls into the real C# TrameClient
// runtime (TrameCall / TrameRestJsonClient / ITrameClient.Call<T> / TrameMultiCallResponse).
// Ported from clients/codegen/src/emitters/cs.ts. The static runtime blocks (Alias, Arg,
// Call, Batch, the root client preamble/footer) are reproduced verbatim from the committed
// snapshot (clients/codegen/test/snapshots/story01.cs/TrameGenerated.cs) as line arrays joined
// by "\n", so the output is byte-for-byte equal to the TS --lang cs emitter — the parity gate
// (CsCodegenParityTests) asserts exactly that. The dynamic parts are the POCOs, the
// per-controller method classes, and the root accessors, assembled from the resolved input.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Trame.Codegen.Core;

internal static class CsEmitter
{
    private const string AutoGeneratedHeader =
        "// <auto-generated> Trame client stub — generated by trame-gen (--lang cs). Do not edit.";

    private static readonly string[] HeaderLines =
    {
        "// Generated from Trame runtime discovery. The C# classes ARE the contract.",
        "// Properties are camelCase on the wire; [JsonPropertyName] maps them to PascalCase POCOs.",
        "// Requires the TrameClient NuGet package (TrameCall, TrameRestJsonClient, ITrameClient).",
        "// The root client is named TrameGeneratedClient (not TrameClient) to avoid a collision",
        "// with the global TrameClient namespace (the runtime's TrameClient.Trame).",
    };

    // Alias + Arg<T> — the typed-alias bridge for batch dependency chains.
    private static readonly string[] AliasLines =
    {
        "    /// <summary>An opaque alias placeholder (the \"@alias\" wire value) produced by",
        "    /// <see cref=\"BatchEntry.Alias\"/>. Implicitly converts into any <see cref=\"Arg{T}\"/>,",
        "    /// so a consumer param accepts <c>order.Alias(\"@customerId\")</c>.</summary>",
        "    public readonly struct Alias",
        "    {",
        "        /// <summary>The wire placeholder string, including the leading '@'.</summary>",
        "        public string Placeholder { get; }",
        "        public Alias(string placeholder) => Placeholder = placeholder;",
        "    }",
        "",
        "    /// <summary>A typed method argument that accepts either a literal value of <typeparamref name=\"T\"/>",
        "    /// or an <see cref=\"Alias\"/> from a producer's <see cref=\"BatchEntry.Alias\"/>. This is the",
        "    /// C# analogue of the TS typed-batch: <c>GetById(Arg&lt;int&gt; id)</c> accepts <c>42</c> and",
        "    /// <c>order.Alias(\"@customerId\")</c> but rejects <c>\"oops\"</c>. The alias→param-type match is",
        "    /// checked at runtime (Roslyn source-generator compile-time check is a future increment).</summary>",
        "    public readonly struct Arg<T>",
        "    {",
        "        private readonly object? _value;",
        "        private Arg(object? value) => _value = value;",
        "",
        "        public static implicit operator Arg<T>(T value) => new(value);",
        "        public static implicit operator Arg<T>(Alias alias) => new(alias);",
        "",
        "        /// <summary>The wire value: the literal, or the \"@alias\" placeholder string for an alias.</summary>",
        "        internal object? ToWireValue() => _value is Alias a ? a.Placeholder : _value;",
        "    }",
    };

    // Call + BatchEntry + Batch — the batch builder (mirrors the TS runtime).
    private static readonly string[] CallLines =
    {
        "    /// <summary>A single Trame call built from a generated controller method. Pass to",
        "    /// <see cref=\"TrameClient.Call{T}\"/> for a single typed call, or to <see cref=\"Batch.Add\"/>",
        "    /// to enroll it in a dependency-chained batch.</summary>",
        "    public sealed class Call",
        "    {",
        "        private readonly TrameCall _call;",
        "        internal Call(TrameCall call) => _call = call;",
        "",
        "        /// <summary>Declare that this call exposes <paramref name=\"jsonPath\"/> as <paramref name=\"alias\"/>.",
        "        /// The wire <c>dependencyMapping</c> key is the alias WITHOUT the leading '@' (the server",
        "        /// strips '@' from a consumer's '@alias' placeholder before lookup), so we strip it here.</summary>",
        "        public Call Exposes(string jsonPath, string alias)",
        "        {",
        "            _call.Exposes(jsonPath, alias.StartsWith('@') ? alias.Substring(1) : alias);",
        "            return this;",
        "        }",
        "",
        "        /// <summary>Set the request id (correlation; used by TrameMultiCallResponse.Get{T}).</summary>",
        "        public Call Named(string id)",
        "        {",
        "            _call.Named(id);",
        "            return this;",
        "        }",
        "",
        "        internal TrameRequest ToRequest() => _call.ToRequest();",
        "    }",
        "",
        "    /// <summary>A call enrolled in a batch. <see cref=\"Exposes\"/> declares an alias the server",
        "    /// resolves from this call's result; <see cref=\"Alias\"/> yields the typed placeholder for a",
        "    /// consumer parameter.</summary>",
        "    public sealed class BatchEntry",
        "    {",
        "        private readonly Call _call;",
        "        internal BatchEntry(Call call) => _call = call;",
        "",
        "        public BatchEntry Exposes(string jsonPath, string alias)",
        "        {",
        "            _call.Exposes(jsonPath, alias);",
        "            return this;",
        "        }",
        "",
        "        /// <summary>Resolve a previously-declared alias to its placeholder (for a consumer param).",
        "        /// Returns the \"@alias\" wire value; <c>Arg&lt;T&gt;</c> converts it implicitly.</summary>",
        "        public Alias Alias(string name) => new(name);",
        "    }",
        "",
        "    /// <summary>Batch builder for dependency-chained calls. Execution mode is Serial (the only",
        "    /// mode that resolves '@alias' placeholders). Add calls in topological order: a producer's",
        "    /// <see cref=\"BatchEntry.Exposes\"/> must run before any consumer's <see cref=\"BatchEntry.Alias\"/>.</summary>",
        "    public sealed class Batch",
        "    {",
        "        private readonly List<Call> _calls = new();",
        "",
        "        public BatchEntry Add(Call call)",
        "        {",
        "            _calls.Add(call);",
        "            return new BatchEntry(call);",
        "        }",
        "",
        "        internal TrameMultiRequest ToMulti() => new()",
        "        {",
        "            Requests = _calls.Select(c => c.ToRequest()).ToList(),",
        "            Mode = ExecutionMode.Serial,",
        "        };",
        "    }",
    };

    // Root TrameGeneratedClient — preamble (before accessors) and footer (after accessors).
    private static readonly string[] RootPreambleLines =
    {
        "    /// <summary>Root generated Trame client. Wraps an <see cref=\"ITrameClient\"/> (a",
        "    /// <see cref=\"TrameRestJsonClient\"/> by default) and exposes one accessor per controller.",
        "    /// Use <see cref=\"Call{T}\"/> for a single typed call, <see cref=\"Batch\"/> for a dependency chain.",
        "    /// Named TrameGeneratedClient to avoid colliding with the global TrameClient namespace.</summary>",
        "    public sealed class TrameGeneratedClient",
        "    {",
        "        private readonly ITrameClient _client;",
        "",
        "        public TrameGeneratedClient(string baseUrl) : this(new TrameRestJsonClient(baseUrl)) { }",
        "",
        "        public TrameGeneratedClient(ITrameClient client) => _client = client;",
    };

    private static readonly string[] RootFooterLines =
    {
        "        /// <summary>Execute a single typed call; the result is deserialized into T.</summary>",
        "        public Task<T?> Call<T>(Call call) => _client.Call<T>(call.ToRequest());",
        "",
        "        /// <summary>Execute a typed batch (Serial — required for @alias resolution). Results are",
        "        /// fetched by request id via <see cref=\"TrameMultiCallResponse.Get{T}\"/>.</summary>",
        "        public Task<TrameMultiCallResponse> Batch(Batch batch) =>",
        "            TrameMultiCallResponse.Call(_client, batch.ToMulti());",
        "    }",
    };

    /// <summary>Emit the C# client as a single TrameGenerated.cs string.</summary>
    public static string Emit(EmitterInput input, EmitCsOptions opts)
    {
        var ns = string.IsNullOrEmpty(opts.Namespace) ? "Trame.Generated" : opts.Namespace!;
        // One shared resolver (mirrors the TS emitter's resolverFor): registered with every type
        // full name, used for both POCO property ref types and method param ref types.
        var resolver = new NamingResolver();
        foreach (var t in input.Types) resolver.Register(t.FullName);

        var sb = new StringBuilder();
        sb.Append(AutoGeneratedHeader).Append('\n');
        sb.Append(string.Join("\n", HeaderLines));
        if (!string.IsNullOrEmpty(opts.BaseUrl))
            sb.Append('\n').Append("// Discovery base URL: ").Append(opts.BaseUrl);
        sb.Append('\n');
        sb.Append("#nullable enable\n");
        sb.Append("using System;\n");
        sb.Append("using System.Collections.Generic;\n");
        sb.Append("using System.Linq;\n");
        sb.Append("using System.Text.Json.Serialization;\n");
        sb.Append("using System.Threading.Tasks;\n");
        sb.Append("using TrameClient.Trame;\n");
        sb.Append("using TrameCommon.Models;\n\n");
        sb.Append("namespace ").Append(ns).Append("\n{\n");

        sb.Append(EmitPocos(input.Types, resolver));
        sb.Append('\n'); // template newline after ${pocos}

        sb.Append(string.Join("\n", AliasLines)).Append("\n\n"); // alias block ends "    }\n\n"
        sb.Append('\n'); // template newline after ${alias}

        sb.Append(string.Join("\n", CallLines)).Append("\n\n"); // call block ends "    }\n\n"
        sb.Append('\n'); // template newline after ${call}

        sb.Append(EmitControllers(input.Controllers, resolver));
        sb.Append("\n\n"); // template "\n\n" between controllers and root

        sb.Append(EmitRootClient(input.Controllers));

        sb.Append("\n}\n"); // namespace close + trailing newline
        return sb.ToString();
    }

    private static string EmitPocos(List<ResolvedType> types, NamingResolver resolver)
    {
        if (types.Count == 0) return "    // No structured types declared in discovery.\n";
        var blocks = new List<string>(types.Count);
        foreach (var t in types) blocks.Add(EmitPoco(t, resolver));
        return string.Join("\n\n", blocks) + "\n";
    }

    private static string EmitPoco(ResolvedType t, NamingResolver resolver)
    {
        var props = new List<string>(t.Properties.Count);
        foreach (var p in t.Properties) props.Add(EmitPocoProperty(p, resolver));
        return "    public class " + t.EmittedName + "\n    {\n" + string.Join("\n", props) + "\n    }";
    }

    private static string EmitPocoProperty(ResolvedProperty p, NamingResolver resolver)
    {
        var ty = EmitterBuilder.Nullable(EmitterBuilder.CsTypeOfRef(p.TypeRef, resolver));
        var propName = Casing.PascalCase(p.DeclaredName);
        var todo = p.TypeRef.Kind == "opaque"
            ? "        // TODO: property \"" + p.DeclaredName + "\" type \"" + (p.TypeRef.NativeName ?? "?") + "\" is an opaque framework/BCL type not modelled in discovery; emitted as object.\n"
            : "";
        var doc = !string.IsNullOrEmpty(p.Documentation) ? "        /// <summary>" + p.Documentation + "</summary>\n" : "";
        return doc + todo + "        [JsonPropertyName(\"" + p.WireName + "\")]\n        public " + ty + " " + propName + " { get; set; }";
    }

    private static string EmitControllers(List<ResolvedController> controllers, NamingResolver resolver)
    {
        if (controllers.Count == 0) return "";
        var blocks = new List<string>(controllers.Count);
        foreach (var c in controllers) blocks.Add(EmitControllerClass(c, resolver));
        return string.Join("\n\n", blocks);
    }

    private static string EmitControllerClass(ResolvedController c, NamingResolver resolver)
    {
        var methods = new List<string>(c.Methods.Count);
        foreach (var m in c.Methods) methods.Add(EmitMethod(c, m, resolver));
        return "    public sealed class " + c.ClassName + "\n    {\n" + string.Join("\n\n", methods) + "\n    }";
    }

    private static string EmitMethod(ResolvedController ctrl, ResolvedMethod m, NamingResolver resolver)
    {
        var parms = new List<string>(m.Parameters.Count);
        foreach (var p in m.Parameters)
            parms.Add("Arg<" + EmitterBuilder.CsTypeOfRef(p.TypeRef, resolver) + "> " + p.Name);
        var paramChain = new StringBuilder();
        foreach (var p in m.Parameters)
            paramChain.Append(".Param(\"" + p.Name + "\", " + p.Name + ".ToWireValue())");
        var doc = !string.IsNullOrEmpty(m.Documentation) ? "        /// <summary>" + m.Documentation + "</summary>\n" : "";
        var todo = (m.ReturnType.Kind == "opaque" && !m.IsVoid)
            ? "        // TODO: return type \"" + (m.ReturnType.NativeName ?? "?") + "\" is an opaque framework/BCL type not modelled in discovery; deserialize as object.\n"
            : "";
        return doc + todo + "        public Call " + m.MethodName + "(" + string.Join(", ", parms) + ") => new Call(TrameCall.Init(\"" + ctrl.Name + "\", \"" + m.MethodName + "\")" + paramChain + ");";
    }

    private static string EmitRootClient(List<ResolvedController> controllers)
    {
        var accessors = controllers.Select(c => "        public " + c.ClassName + " " + c.Name + " { get; } = new();");
        return string.Join("\n", RootPreambleLines) + "\n\n" + string.Join("\n", accessors) + "\n\n" + string.Join("\n", RootFooterLines);
    }
}