// C# emitter — emits a single TrameGenerated.cs that calls into the real C#
// TrameClient runtime (TrameCall / TrameRestJsonClient / ITrameClient.Call<T> /
// TrameMultiCallResponse). No duplicated REST client.
//
// Headline value: a typed batch builder. Each generated method takes `Arg<T>`
// params — `Arg<int>` accepts `42` and `order.Alias("@customerId")` but rejects
// `"oops"`. `Batch` + `exposes`/`Alias` mirror the TS runtime; the wire
// `dependencyMapping` key is the alias WITHOUT the leading `@` (the server
// strips `@` from a consumer's `@alias` placeholder before lookup — see
// TrameInvoker.ReplaceDependencyByAliasCore), and `Alias(name)` carries the
// `@x` placeholder that `Arg<T>.ToWireValue()` returns so `Param(name,"@x")`
// is wire-identical to `TrameCall.WithAlias("@x")`.
//
// Compile-time JSON-path validation is deferred to a future Roslyn source-
// generator phase (C# has no template-literal types); C# Increment 2 = typed
// POCOs + typed params + typed result deser + batch + runtime exposes/alias.

import type { EmitterInput, ResolvedController, ResolvedMethod, ResolvedProperty, ResolvedTypeRef } from "../core/model.js";
import { csTypeOfRef } from "../core/model.js";
import { NamingResolver } from "../core/naming.js";

export interface EmitCsOptions {
  /** C# namespace for the generated file (default "Trame.Generated"). */
  namespace?: string;
  /** Base URL hint rendered into the file header comment. */
  baseUrl?: string;
}

/** Emit the C# client as a single-file tree (`{ "TrameGenerated.cs": … }`). */
export function emitCsClient(input: EmitterInput, opts: EmitCsOptions = {}): Record<string, string> {
  const ns = opts.namespace ?? "Trame.Generated";
  const resolver = resolverFor(input);
  return { "TrameGenerated.cs": emitFile(input, resolver, ns, opts.baseUrl) };
}

function resolverFor(input: EmitterInput): NamingResolver {
  const r = new NamingResolver();
  for (const t of input.types) r.register(t.fullName);
  return r;
}

function emitFile(input: EmitterInput, resolver: NamingResolver, ns: string, baseUrl?: string): string {
  const header = emitHeader(baseUrl);
  const pocos = emitPocos(input, resolver);
  const alias = emitAliasAndArg();
  const call = emitCallAndBatch();
  const controllers = input.controllers.map((c) => emitControllerClass(c, resolver)).join("\n\n");
  const root = emitRootClient(input);
  return `// <auto-generated> Trame client stub — generated by trame-gen (--lang cs). Do not edit.
${header}
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using TrameClient.Trame;
using TrameCommon.Models;

namespace ${ns}
{
${pocos}
${alias}
${call}
${controllers}

${root}
}
`;
}

function emitHeader(baseUrl?: string): string {
  const lines = ["// Generated from Trame runtime discovery. The C# classes ARE the contract.",
    "// Properties are camelCase on the wire; [JsonPropertyName] maps them to PascalCase POCOs.",
    "// Requires the TrameClient NuGet package (TrameCall, TrameRestJsonClient, ITrameClient).",
    "// The root client is named TrameGeneratedClient (not TrameClient) to avoid a collision",
    "// with the global TrameClient namespace (the runtime's TrameClient.Trame)."];
  if (baseUrl) lines.push(`// Discovery base URL: ${baseUrl}`);
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// POCOs — one class per ResolvedType (nullable props, [JsonPropertyName] wire).
// ---------------------------------------------------------------------------

function emitPocos(input: EmitterInput, resolver: NamingResolver): string {
  if (input.types.length === 0) return "    // No structured types declared in discovery.\n";
  const blocks = input.types.map((t) => emitPoco(t, resolver));
  return blocks.join("\n\n") + "\n";
}

function emitPoco(t: { emittedName: string; properties: ResolvedProperty[] }, resolver: NamingResolver): string {
  const props = t.properties.map((p) => emitPocoProperty(p, resolver));
  return `    public class ${t.emittedName}\n    {\n${props.join("\n")}\n    }`;
}

function emitPocoProperty(p: ResolvedProperty, resolver: NamingResolver): string {
  const ty = nullable(csTypeOfRef(p.typeRef, resolver));
  const propName = pascalName(p.declaredName);
  const todo = p.typeRef.kind === "opaque"
    ? `        // TODO: property "${p.declaredName}" type "${p.typeRef.nativeName ?? "?"}" is an opaque framework/BCL type not modelled in discovery; emitted as object.\n`
    : "";
  const doc = p.documentation ? `        /// <summary>${p.documentation}</summary>\n` : "";
  return `${doc}${todo}        [JsonPropertyName("${p.wireName}")]\n        public ${ty} ${propName} { get; set; }`;
}

/** Append `?` to a POCO property type (discovery carries no nullability; callers narrow). */
function nullable(ty: string): string {
  return ty.endsWith("?") ? ty : `${ty}?`;
}

/** PascalCase a declared property name (`customerId` → `CustomerId`). */
function pascalName(name: string): string {
  if (!name) return name;
  return name.charAt(0).toUpperCase() + name.slice(1);
}

// ---------------------------------------------------------------------------
// Alias + Arg<T> — the typed-alias bridge for batch dependency chains.
// ---------------------------------------------------------------------------

function emitAliasAndArg(): string {
  return `    /// <summary>An opaque alias placeholder (the "@alias" wire value) produced by
    /// <see cref="BatchEntry.Alias"/>. Implicitly converts into any <see cref="Arg{T}"/>,
    /// so a consumer param accepts <c>order.Alias("@customerId")</c>.</summary>
    public readonly struct Alias
    {
        /// <summary>The wire placeholder string, including the leading '@'.</summary>
        public string Placeholder { get; }
        public Alias(string placeholder) => Placeholder = placeholder;
    }

    /// <summary>A typed method argument that accepts either a literal value of <typeparamref name="T"/>
    /// or an <see cref="Alias"/> from a producer's <see cref="BatchEntry.Alias"/>. This is the
    /// C# analogue of the TS typed-batch: <c>GetById(Arg&lt;int&gt; id)</c> accepts <c>42</c> and
    /// <c>order.Alias("@customerId")</c> but rejects <c>"oops"</c>. The alias→param-type match is
    /// checked at runtime (Roslyn source-generator compile-time check is a future increment).</summary>
    public readonly struct Arg<T>
    {
        private readonly object? _value;
        private Arg(object? value) => _value = value;

        public static implicit operator Arg<T>(T value) => new(value);
        public static implicit operator Arg<T>(Alias alias) => new(alias);

        /// <summary>The wire value: the literal, or the "@alias" placeholder string for an alias.</summary>
        internal object? ToWireValue() => _value is Alias a ? a.Placeholder : _value;
    }

`;
}

// ---------------------------------------------------------------------------
// Call + BatchEntry + Batch — the batch builder (mirrors the TS runtime).
// ---------------------------------------------------------------------------

function emitCallAndBatch(): string {
  return `    /// <summary>A single Trame call built from a generated controller method. Pass to
    /// <see cref="TrameClient.Call{T}"/> for a single typed call, or to <see cref="Batch.Add"/>
    /// to enroll it in a dependency-chained batch.</summary>
    public sealed class Call
    {
        private readonly TrameCall _call;
        internal Call(TrameCall call) => _call = call;

        /// <summary>Declare that this call exposes <paramref name="jsonPath"/> as <paramref name="alias"/>.
        /// The wire <c>dependencyMapping</c> key is the alias WITHOUT the leading '@' (the server
        /// strips '@' from a consumer's '@alias' placeholder before lookup), so we strip it here.</summary>
        public Call Exposes(string jsonPath, string alias)
        {
            _call.Exposes(jsonPath, alias.StartsWith('@') ? alias.Substring(1) : alias);
            return this;
        }

        /// <summary>Set the request id (correlation; used by TrameMultiCallResponse.Get{T}).</summary>
        public Call Named(string id)
        {
            _call.Named(id);
            return this;
        }

        internal TrameRequest ToRequest() => _call.ToRequest();
    }

    /// <summary>A call enrolled in a batch. <see cref="Exposes"/> declares an alias the server
    /// resolves from this call's result; <see cref="Alias"/> yields the typed placeholder for a
    /// consumer parameter.</summary>
    public sealed class BatchEntry
    {
        private readonly Call _call;
        internal BatchEntry(Call call) => _call = call;

        public BatchEntry Exposes(string jsonPath, string alias)
        {
            _call.Exposes(jsonPath, alias);
            return this;
        }

        /// <summary>Resolve a previously-declared alias to its placeholder (for a consumer param).
        /// Returns the "@alias" wire value; <c>Arg&lt;T&gt;</c> converts it implicitly.</summary>
        public Alias Alias(string name) => new(name);
    }

    /// <summary>Batch builder for dependency-chained calls. Execution mode is Serial (the only
    /// mode that resolves '@alias' placeholders). Add calls in topological order: a producer's
    /// <see cref="BatchEntry.Exposes"/> must run before any consumer's <see cref="BatchEntry.Alias"/>.</summary>
    public sealed class Batch
    {
        private readonly List<Call> _calls = new();

        public BatchEntry Add(Call call)
        {
            _calls.Add(call);
            return new BatchEntry(call);
        }

        internal TrameMultiRequest ToMulti() => new()
        {
            Requests = _calls.Select(c => c.ToRequest()).ToList(),
            Mode = ExecutionMode.Serial,
        };
    }

`;
}

// ---------------------------------------------------------------------------
// Per-controller classes — methods return Call, params are Arg<T>.
// ---------------------------------------------------------------------------

function emitControllerClass(ctrl: ResolvedController, resolver: NamingResolver): string {
  const methods = ctrl.methods.map((m) => emitMethod(ctrl, m, resolver));
  return `    public sealed class ${ctrl.className}\n    {\n${methods.join("\n\n")}\n    }`;
}

function emitMethod(ctrl: ResolvedController, m: ResolvedMethod, resolver: NamingResolver): string {
  const params = m.parameters.map((p) => {
    const ty = csTypeOfRef(p.typeRef, resolver);
    return `Arg<${ty}> ${p.name}`;
  });
  const paramChain = m.parameters.map((p) => `.Param("${p.name}", ${p.name}.ToWireValue())`).join("");
  const doc = m.documentation ? `        /// <summary>${m.documentation}</summary>\n` : "";
  const todo = m.returnType.kind === "opaque" && !m.isVoid
    ? `        // TODO: return type "${m.returnType.nativeName ?? "?"}" is an opaque framework/BCL type not modelled in discovery; deserialize as object.\n`
    : "";
  return `${doc}${todo}        public Call ${m.methodName}(${params.join(", ")}) => new Call(TrameCall.Init("${ctrl.name}", "${m.methodName}")${paramChain});`;
}

// ---------------------------------------------------------------------------
// Root TrameClient — per-controller accessors + Call<T> + Batch.
// ---------------------------------------------------------------------------

function emitRootClient(input: EmitterInput): string {
  const accessors = input.controllers.map((c) =>
    `        public ${c.className} ${c.name} { get; } = new();`);
  return `    /// <summary>Root generated Trame client. Wraps an <see cref="ITrameClient"/> (a
    /// <see cref="TrameRestJsonClient"/> by default) and exposes one accessor per controller.
    /// Use <see cref="Call{T}"/> for a single typed call, <see cref="Batch"/> for a dependency chain.
    /// Named TrameGeneratedClient to avoid colliding with the global TrameClient namespace.</summary>
    public sealed class TrameGeneratedClient
    {
        private readonly ITrameClient _client;

        public TrameGeneratedClient(string baseUrl) : this(new TrameRestJsonClient(baseUrl)) { }

        public TrameGeneratedClient(ITrameClient client) => _client = client;

${accessors.join("\n")}

        /// <summary>Execute a single typed call; the result is deserialized into T.</summary>
        public Task<T?> Call<T>(Call call) => _client.Call<T>(call.ToRequest());

        /// <summary>Execute a typed batch (Serial — required for @alias resolution). Results are
        /// fetched by request id via <see cref="TrameMultiCallResponse.Get{T}"/>.</summary>
        public Task<TrameMultiCallResponse> Batch(Batch batch) =>
            TrameMultiCallResponse.Call(_client, batch.ToMulti());
    }`;
}