<script lang="ts">
  import { onDestroy } from 'svelte';
  import { discoveryState } from '../../state/discovery.svelte.ts';
  // All three languages are generated by the shared sleipnir-codegen core (the same
  // engine `npx sleipnir-gen` uses), so the wire-correctness fixes (camelCase props,
  // camelCase method names, per-controller classes, typed batch, the @-strip on
  // exposes) live in one place. The core emits a multi-file tree; the DevUI
  // renders a single <pre>, so the files are concatenated with `// ===== file:
  // path =====` banners (same shape the CLI's `--stdout` mode produces).
  import {
    buildEmitterInput,
    NamingResolver,
    emitTsClient,
    emitCsClient,
    emitPyClient,
  } from 'sleipnir-codegen';

  let activeLang = $state<'ts' | 'cs' | 'py'>('ts');
  let copied = $state('');
  let copyTimer = $state<ReturnType<typeof setTimeout> | null>(null);

  onDestroy(() => {
    if (copyTimer) clearTimeout(copyTimer);
  });

  const LANG_LABEL: Record<'ts' | 'cs' | 'py', string> = {
    ts: 'TypeScript',
    cs: 'C#',
    py: 'Python',
  };

  // Concatenate a core-emitted file tree with file banners (mirrors `--stdout`).
  function renderTree(tree: Record<string, string>): string {
    return Object.entries(tree)
      .map(([path, content]) => `// ===== file: ${path} =====\n${content}`)
      .join('\n');
  }

  function generateTs(): string {
    const data = discoveryState.data;
    if (!data || (data.controllers ?? []).length === 0) return '// No controllers discovered.';
    return renderTree(emitTsClient(buildEmitterInput(data, new NamingResolver())));
  }

  function generateCs(): string {
    const data = discoveryState.data;
    if (!data || (data.controllers ?? []).length === 0) return '// No controllers discovered.';
    return renderTree(emitCsClient(buildEmitterInput(data, new NamingResolver())));
  }

  function generatePy(): string {
    const data = discoveryState.data;
    if (!data || (data.controllers ?? []).length === 0) return '# No controllers discovered.';
    return renderTree(emitPyClient(buildEmitterInput(data, new NamingResolver())));
  }

  function generate(): string {
    if (activeLang === 'ts') return generateTs();
    if (activeLang === 'cs') return generateCs();
    return generatePy();
  }

  let code = $derived(generate());

  async function copy() {
    try {
      await navigator.clipboard.writeText(code);
      copied = activeLang;
      if (copyTimer) clearTimeout(copyTimer);
      copyTimer = setTimeout(() => { copied = ''; copyTimer = null; }, 1500);
    } catch { /* ignore */ }
  }
</script>

<div class="codegen-page">
  <div class="codegen-header">
    <div class="lang-tabs">
      <button
        class="ghost small"
        class:active={activeLang === 'ts'}
        onclick={() => (activeLang = 'ts')}
      >TypeScript</button>
      <button
        class="ghost small"
        class:active={activeLang === 'cs'}
        onclick={() => (activeLang = 'cs')}
      >C#</button>
      <button
        class="ghost small"
        class:active={activeLang === 'py'}
        onclick={() => (activeLang = 'py')}
      >Python</button>
    </div>
    <button class="primary small" onclick={copy}>
      {copied === activeLang ? 'Copied!' : `Copy ${LANG_LABEL[activeLang]}`}
    </button>
  </div>
  <pre class="code codegen-output"><code>{code}</code></pre>
</div>

<style>
  .codegen-page {
    display: flex;
    flex-direction: column;
    height: 100%;
    min-height: 0;
  }
  .codegen-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 8px;
    flex-shrink: 0;
  }
  .lang-tabs {
    display: flex;
    gap: 2px;
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    overflow: hidden;
  }
  .lang-tabs button {
    border: none;
    border-radius: 0;
    padding: 4px 12px;
  }
  .lang-tabs button.active {
    background: var(--accent-secondary);
    color: #fff;
  }
  .codegen-output {
    flex: 1;
    min-height: 0;
    overflow: auto;
    padding: 12px;
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    background: var(--code-bg);
    color: var(--code-text);
    font-family: var(--font-mono);
    font-size: 0.82rem;
    line-height: 1.6;
    white-space: pre;
    margin: 0;
  }
  .codegen-output code {
    font-family: var(--font-mono);
  }
</style>
