<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NotificationChat.Client</AssemblyName>
    <RootNamespace>Sleipnir.Samples.NotificationChat.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sleipnir.Client" Version="1.4.3" />
  </ItemGroup>

</Project>
