<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NotificationChat.Client</AssemblyName>
    <RootNamespace>Trame.Samples.NotificationChat.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Trame.Client" Version="1.0.0" />
  </ItemGroup>

</Project>
