using System.Text;
using System.Text.Json;

namespace Trame.Spike.LinqProvider;

/// <summary>
/// Erzeugt aus einer Discovery-JSON (/api/trame/discovery) typsichere C#-Verträge —
/// das "discovery-generiert"-Modell (Option c). Für jede gefundene Controller-
/// Methode wird eine Interface-Methode mit korrekten Parametertypen und dem
/// <see cref="TrameServiceContractAttribute"/> / <see cref="TrameMethodContractAttribute"/>
/// ausgegeben. Task&lt;T&gt; wird zu T entpackt, CancellationToken entfernt, void-Methoden
/// zu Task.
///
/// Der Prototyp liest die JSON direkt und gibt einen C#-Quelltext-String zurück;
/// in einem echten Setup liefe dies als Build-Tool (dotnet tool / Source-Generator)
/// und schriebe Contracts.g.cs auf Platte. Siehe <see cref="Contracts.cs"/> für
/// den repräsentativen Output gegen den Customer-Controller.
/// </summary>
public static class ContractGenerator
{
    /// <summary>Erzeugt den C#-Vertrags-Quelltext für alle Controller der Discovery.</summary>
    public static string Generate(string discoveryJson)
    {
        using var doc = JsonDocument.Parse(discoveryJson);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>Erzeugt aus /api/trame/discovery von ContractGenerator.</auto-generated>");
        sb.AppendLine("namespace Trame.Spike.LinqProvider;");
        sb.AppendLine();

        foreach (var ctrl in doc.RootElement.GetProperty("controllers").EnumerateArray())
        {
            var name = ctrl.GetProperty("name").GetString()!;
            var iface = InterfaceNameForController(name);
            sb.AppendLine($"/// <summary>Vertrag für den {name}-Controller.</summary>");
            sb.AppendLine($"[TrameServiceContract(\"{name}\")]");
            sb.AppendLine($"public interface {iface}");
            sb.AppendLine("{");
            foreach (var m in ctrl.GetProperty("methods").EnumerateArray())
            {
                var method = m.GetProperty("methodName").GetString()!;
                var ret = m.GetProperty("returnType").GetString() ?? "void";
                var (csRet, isTask) = MapReturnType(ret);
                var paramTypes = m.TryGetProperty("parameters", out var p)
                    ? p.EnumerateArray().Where(x => x.GetProperty("parameterType").GetString() != "CancellationToken")
                        .Select(x => $"Arg<{MapType(x.GetProperty("parameterType").GetString()!)}> {x.GetProperty("parameterName").GetString()}")
                        .ToArray()
                    : Array.Empty<string>();
                sb.AppendLine($"    [TrameMethodContract(\"{method}\")]");
                sb.AppendLine($"    {csRet} {MethodNameFor(method)}({string.Join(", ", paramTypes)});");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    private static string InterfaceNameForController(string controller) =>
        "I" + controller + "Service";

    // C#-Methodenname = serverseitiger Methodenname (1:1). Ein echter Generator
    // könnte hier camelCase→PascalCase normalisieren.
    private static string MethodNameFor(string method) => method;

    private static (string csType, bool isTask) MapReturnType(string ret)
    {
        if (ret == "Void" || string.IsNullOrEmpty(ret)) return ("Task", true);
        return ("Task<" + MapType(ret) + "?>", true);
    }

    /// <summary>Übersetzt friendly Discovery-Typnamen in C#-Typnamen.</summary>
    public static string MapType(string type)
    {
        if (string.IsNullOrEmpty(type)) return "object";
        if (type == "int") return "int";
        if (type == "string") return "string";
        if (type == "bool") return "bool";
        if (type == "decimal") return "decimal";
        if (type == "double") return "double";
        if (type == "long") return "long";
        if (type == "float") return "float";
        if (type == "DateTime") return "DateTime";
        if (type == "Guid") return "Guid";
        if (type == "byte[]") return "byte[]";
        // List<X> -> List<X>, X[] -> X[], sonst unverändert (Klassenname).
        return type;
    }
}