<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NotificationChat.Server</AssemblyName>
    <RootNamespace>Sleipnir.Samples.NotificationChat.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sleipnir.Server" Version="1.0.0" />
  </ItemGroup>

</Project>
