syntax = "proto3";

option csharp_namespace = "Trame.Grpc";

service CustomerGrpc {
  rpc GetAllCustomers (Empty) returns (CustomerList);
  rpc GetCustomerById (CustomerRequest) returns (Customer);
  rpc AddCustomer (AddCustomerRequest) returns (AddCustomerResponse);
  rpc GetOrdersByOrderId (OrderRequest) returns (OrderList);
}

message Empty {}

message CustomerRequest {
  int32 id = 1;
}

message AddCustomerRequest {
  string name = 1;
}

message AddCustomerResponse {
  int32 id = 1;
}

message OrderRequest {
  int32 id = 1;
}

message Customer {
  int32 id = 1;
  int32 order_id = 2;
  string name = 3;
  int64 created = 4;
  string resource_id = 5;
  repeated Address addresses = 6;
}

message Address {
  int32 id = 1;
  string street = 2;
  string city = 3;
  string postal_code = 4;
}

message Order {
  int32 id = 1;
  string product_name = 2;
  double price = 3;
}

message CustomerList {
  repeated Customer customers = 1;
}

message OrderList {
  repeated Order orders = 1;
}